### ISSUE TITLE
Command line to run prod-system?

### ISSUE THREAD

**Issue by colliderwriter** [danielsz/holygrail#1]
If there's a way to run prod-system from the command line, I can't find it. It's so conspicuous that I think I must be misunderstanding, in which case I guess this is a plea for another sentence in the README.

**Comment by danielsz** [comment]
I was not sure if I had to include a `prod-run`task, if it was in the scope of the tutorial, but now it is obvious that it should be there. Fixed in commit 93d26598ec9c5f22b46dc9dadaa44cb01ec03a3a

I'm not sure where you would have liked to encountered the sentence in the README. It would be great if you could formulate the sentence that would have helped you. PR would be best.

Thanks!

**Comment by colliderwriter** [comment]
Your commit is roughly what I would expect to have seen. I was puzzled by its absence but the code is clear enough. 

My last question: if this code is jarred and then run with "java -jar...", it will execute from the main-, correct?

**Comment by danielsz** [comment]
Yes, but you need the tell in what namespace the `-main` function is to be found.

https://github.com/adzerk-oss/boot-uberjar-example

Also: https://github.com/danielsz/system/blob/master/examples/boot/build.boot

**Comment by colliderwriter** [comment]
Perfect. Thanks for taking the time to explain
